

# This file was *autogenerated* from the file sage/lwechal-est/lwechal-bkz-only.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2)
load("../framework/est/lwechal-est.sage")

######################################
#set method parameters
'''
    
    method = 1: progressive bkz estimation.
             2: two step mode
             3: bkz-only with fixed blocksize
             4: default g6k
             
    progressive_sieve = True:  progressive sieve

    cost_model = 1: theoretical cost estimation
               = 2: experimental cost estimation
'''
#######################################
#Fixed parameters
method = _sage_const_3 
cost_model = _sage_const_2 
worst_case = True
#------------------------------------

lwechal_est(method,  cost_model, worst_case)

