

# This file was *autogenerated* from the file lwechal-pro-bkz2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_40 = Integer(40); _sage_const_0p020 = RealNumber('0.020'); _sage_const_0p025 = RealNumber('0.025'); _sage_const_0p030 = RealNumber('0.030'); _sage_const_0p035 = RealNumber('0.035'); _sage_const_0p040 = RealNumber('0.040'); _sage_const_45 = Integer(45); _sage_const_50 = Integer(50); _sage_const_55 = Integer(55); _sage_const_60 = Integer(60); _sage_const_65 = Integer(65); _sage_const_70 = Integer(70); _sage_const_75 = Integer(75); _sage_const_80 = Integer(80)
load("../framework/est/lwechal-est.sage")

######################################
#set method parameters
'''
    
    method = 1: progressive bkz estimation.
             2: two step mode
             3: bkz-only with fixed blocksize
             4: default g6k
             
    progressive_sieve = True:  progressive sieve

    cost_model = 1: theoretical cost estimation
               = 2: experimental cost estimation

    :cumG : False: [PV21] estimate
            True: cumulated gate estimate adaptive to [PV21]
'''

'''
#######################################
#Fixed parameters
method = 1
cost_model = 1
worst_case = True
#------------------------------------

lwechal_est(method,  cost_model, worst_case)
'''


#######################################
#Fixed parameters
method = _sage_const_1 
cost_model = _sage_const_1 
ldc_param = "MATZOV22"
worst_case = False
cumG = True
#------------------------------------

lwechals = [(_sage_const_40 ,_sage_const_0p020 ), (_sage_const_40 ,_sage_const_0p025 ), (_sage_const_40 ,_sage_const_0p030 ), (_sage_const_40 ,_sage_const_0p035 ), (_sage_const_40 ,_sage_const_0p040 ), 
            (_sage_const_45 ,_sage_const_0p020 ), (_sage_const_45 ,_sage_const_0p025 ), (_sage_const_45 ,_sage_const_0p030 ), (_sage_const_45 ,_sage_const_0p035 ), (_sage_const_45 ,_sage_const_0p040 ), 
            (_sage_const_50 ,_sage_const_0p020 ), (_sage_const_50 ,_sage_const_0p025 ), (_sage_const_50 ,_sage_const_0p030 ), (_sage_const_50 ,_sage_const_0p035 ), (_sage_const_50 ,_sage_const_0p040 ), 
            (_sage_const_55 ,_sage_const_0p020 ), (_sage_const_55 ,_sage_const_0p025 ), (_sage_const_55 ,_sage_const_0p030 ), (_sage_const_55 ,_sage_const_0p035 ), (_sage_const_55 ,_sage_const_0p040 ), 
            (_sage_const_60 ,_sage_const_0p020 ), (_sage_const_60 ,_sage_const_0p025 ), (_sage_const_60 ,_sage_const_0p030 ), (_sage_const_60 ,_sage_const_0p035 ), (_sage_const_60 ,_sage_const_0p040 ), 
            (_sage_const_65 ,_sage_const_0p020 ), (_sage_const_65 ,_sage_const_0p025 ), (_sage_const_65 ,_sage_const_0p030 ), (_sage_const_65 ,_sage_const_0p035 ), (_sage_const_65 ,_sage_const_0p040 ),
            (_sage_const_70 ,_sage_const_0p020 ), (_sage_const_70 ,_sage_const_0p025 ), (_sage_const_70 ,_sage_const_0p030 ), (_sage_const_70 ,_sage_const_0p035 ), (_sage_const_70 ,_sage_const_0p040 ), 
            (_sage_const_75 ,_sage_const_0p020 ), (_sage_const_75 ,_sage_const_0p025 ), (_sage_const_75 ,_sage_const_0p030 ), (_sage_const_75 ,_sage_const_0p035 ), (_sage_const_75 ,_sage_const_0p040 ), 
            (_sage_const_80 ,_sage_const_0p020 ), (_sage_const_80 ,_sage_const_0p025 ), (_sage_const_80 ,_sage_const_0p030 ), (_sage_const_80 ,_sage_const_0p035 ), (_sage_const_80 ,_sage_const_0p040 )] 
lwechal_est(lwechals, method,  cost_model, worst_case, cumG = cumG)

