

# This file was *autogenerated* from the file mimabisai_est.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_6 = Integer(6); _sage_const_7 = Integer(7); _sage_const_120 = Integer(120); _sage_const_256 = Integer(256); _sage_const_1 = Integer(1); _sage_const_2p = RealNumber('2.'); _sage_const_0 = Integer(0); _sage_const_8 = Integer(8); _sage_const_3 = Integer(3)
from timu import timu

load("../framework/est/NIST-est.sage")


method = _sage_const_2 
worst_case = False
ldc_param = "MATZOV22"
goal_min_cost = "gate_min"
cal_ee = "chi"






saitinumber = _sage_const_6 
n, q, m, _, _, target_norm = timu(saitinumber)
eta1 = _sage_const_2 
eta2 = _sage_const_2 
D_s =build_centered_binomial_law(eta1) 
D_e = build_centered_binomial_law(eta2) 

dim_, dvol = initialize_from_LWE_instance(n, q, m, D_e, D_s)
svp_estimate_attack(method=method, ldc_param =  ldc_param, cal_ee = cal_ee, goal_min_cost = goal_min_cost, worst_case = worst_case, dvol = dvol, dim_ = dim_)



saitinumber = _sage_const_7 
n, q, m, _, _, target_norm = timu(saitinumber)
eta2 = _sage_const_2 
t = _sage_const_120 
p = _sage_const_256 
D_s = {_sage_const_1 : t/(_sage_const_2p *p), -_sage_const_1 : t/(_sage_const_2p *p), _sage_const_0 : (p -t)/p} #SparseTernary: t/2 entries of 1,  t/2 entries of -1, rest is 0.
D_e = build_centered_binomial_law(eta2) 

dim_, dvol = initialize_from_LWE_instance(n, q, m, D_e, D_s)
svp_estimate_attack(method=method, ldc_param =  ldc_param, cal_ee = cal_ee, goal_min_cost = goal_min_cost, worst_case = worst_case, dvol = dvol, dim_ = dim_)



saitinumber = _sage_const_8 
n, q, m, _, _, target_norm = timu(saitinumber)
n = _sage_const_2 *n
m = _sage_const_2 *m
eta1 = _sage_const_3 
eta2 = _sage_const_2     
D_s =build_centered_binomial_law(eta1) 
D_e = build_centered_binomial_law(eta2) 

dim_, dvol = initialize_from_LWE_instance(n, q, m, D_e, D_s)
svp_estimate_attack(method=method, ldc_param =  ldc_param, cal_ee = cal_ee, goal_min_cost = goal_min_cost, worst_case = worst_case, dvol = dvol, dim_ = dim_)


