#include "attack.h"

//estimate using gs-lengths generated by gsa.
void gsa_est(int dim, FP_NR<FT> dvol, Params* params);

//lwe challenges estimation
vector<LWEchal> load_unsolved_lwechallenges();
void lwechal_est(LWEchal lwechal, Params* params);

